### ISSUE TITLE
Error when member sends message to Bot

### ISSUE THREAD

**Issue by PallavBS** [verixx/modmail#16]
Ignoring exception in on_message
2017-10-30T06:25:16.385698+00:00 app[worker.1]: Traceback (most recent call last):
2017-10-30T06:25:16.385702+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 223, in _run_event
2017-10-30T06:25:16.385703+00:00 app[worker.1]:     yield from coro(*args, **kwargs)
2017-10-30T06:25:16.385737+00:00 app[worker.1]:   File "bot.py", line 366, in on_message
2017-10-30T06:25:16.385738+00:00 app[worker.1]:     await self.process_modmail(message)
2017-10-30T06:25:16.385757+00:00 app[worker.1]:   File "bot.py", line 335, in process_modmail
2017-10-30T06:25:16.385759+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2017-10-30T06:25:16.385797+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'

**Comment by PallavBS** [comment]
**Fixed: **
Line 225 in bot.py
Replace `channel = discord.utils.get(guild.**text.**channels, topic=topic)`
with `channel = discord.utils.get(guild.channels, topic=topic)`
